version: 2
jobs:
  build:
    working_directory: /usr/share/nginx/html
    docker:
      - image: sujeetk94/devops
        environment:
          APP_ENV: test
    steps:
      - run:
          name: Install system packages
          command: apt-get update && apt-get -y install git
      - run:
          name: checking 
          command: mkdir -p /usr/share/nginx/html/sujeet
      - run:
          name: running 
          command: docker run -it -p 80:80 --name=devops -d sujeetk94/devops
      - run:
          name: commit
          command: docker commit devops sujeetk94/devops:circleci
      - run:
          name: push to hub
          command: docker push sujeetk94/devops:cirlceci
